CREATE TABLE guilds (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    prefix VARCHAR(5) NOT NULL DEFAULT 'z',
    language VARCHAR(2) NOT NULL DEFAULT 'en',
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY,
    voice_name VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE temp_voices (
    id VARCHAR(36) PRIMARY KEY,
    guild_id VARCHAR(36) NOT NULL,
    author_id VARCHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE,
    INDEX (guild_id)
);

CREATE TABLE temp_voice_creators (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    guild_id VARCHAR(36) NOT NULL,
    FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE,
    INDEX (guild_id)
);
