CREATE TABLE guilds (
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	prefix VARCHAR(5) NOT NULL DEFAULT 'z',
	language VARCHAR(2) NOT NULL DEFAULT 'en',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE temp_vcs (
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	author_id VARCHAR(36) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE creator_vcs {
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
}

CREATE TABLE users {
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	vc_name VARCHAR(255),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
}
