CREATE TABLE guilds (
	id VARCHAR(255) NOT NULL PRIMARY KEY,
	prefix VARCHAR(5) NOT NULL DEFAULT 'z',
	language VARCHAR(6) NOT NULL DEFAULT 'en-us',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
