CREATE TABLE guilds (
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	prefix VARCHAR(5) NOT NULL DEFAULT 'z',
	language VARCHAR(2) NOT NULL DEFAULT 'en',
	active BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);

CREATE TABLE voice (
	id INT(32) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	guild_id VARCHAR(36) NOT NULL,
	author_id VARCHAR(36) NOT NULL,
	name VARCHAR(128) NOT NULL,
	started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ended_at TIMESTAMP NULL,
	FOREIGN KEY (guild_id) REFERENCES guilds(id)
);

CREATE TABLE voices_participants (
	id INT(32) NOT NULL PRIMARY KEY,
	member_id VARCHAR(36) NOT NULL,
	joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	left_at TIMESTAMP NULL,
	FOREIGN KEY (id) REFERENCES voice(id)
);
